CREATE DATABASE CUSTOMER_ANALYSIS;

SELECT * FROM customertable LIMIT 10;

-- Q1. What is the total revenue generated by male and female customers ?
SELECT gender, SUM(purchase_amount) as REVENUE 
FROM customertable
GROUP BY gender;

-- Q2. which customer used discount but still spent more than the average purchase amount ?
SELECT customer_id, purchase_amount
from customertable
WHERE discount_applied ="Yes" and purchase_amount>(SELECT AVG(purchase_amount) FROM customertable);

-- Q3. which are the top 5 products with highest average review rating?
SELECT item_purchased, ROUND(avg(review_rating),2) as "average product rating"
FROM customertable
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare average purchase amount between standard and express shipping?
SELECT shipping_type, ROUND(AVG(purchase_amount),2) as "Average purchase amount"
FROM customertable
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- practise
-- SELECT shipping_type, ROUND(AVG(purchase_amount),2) as "Average purchase amount"
-- FROM customertable
-- GROUP BY shipping_type
-- ORDER BY ROUND(AVG(purchase_amount),2) DESC

-- Q5. Do subscribered customer spend more ? compare average spent and total revenue between subscribers and non-subscribers?
SELECT subscription_status, COUNT(customer_id) as "total_customers",
ROUND(AVG(purchase_amount),2) as "average_spend",
SUM(purchase_amount) as "total_revenue"
from customertable
group by subscription_status
order by average_spend, total_revenue DESC;

-- Q6. which 5 products have highest percentage of purchase with discount applied?
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied="Yes" THEN 1 ELSE 0 END)/count(*),2) as "purchase_percentage"
FROM customertable
group by item_purchased
order by purchase_percentage DESC
limit 5;

-- Q7. Segment customers into new,returning and loyal based on the number of previous purchase and show count for each segment?
with customer_type as (select customer_id,previous_purchases,
CASE
    WHEN previous_purchases=1 THEN "New"
    WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
    ELSE "LOYAL"
    END as customer_segment
from customertable
)

select customer_segment,count(*) as "number of customer"
from customer_type
group by customer_segment;

-- Q8. what are top 3 most puchased products within each category-- 
WITH item_counts as (
select category, 
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customertable
group by category ,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3;

-- Q9. Are customers who are repeate buyers(more than 5 previous purchase) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customertable
where previous_purchases >5
group by subscription_status;

-- Q10. What is the revenue contribution by each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customertable
group by age_group
order by total_revenue DESC;


